### ISSUE TITLE
Difference of intonation

### ISSUE THREAD

**Issue by pinkywafer** [pinkywafer/OpenTX_soundpack-Joanne#2]
Between Armed and disarmed

**Comment by Teracis** [comment]
I've made an edit for disarmed that sounds a lot closer to what I had from the amber pack. It's a little disjointed still but it works.

[darmed.zip](https://github.com/pinkywafer/OpenTX_soundpack-Joanne/files/1050311/darmed.zip)

 I used the dis from disabled and attached it to armed.

I had typed out this reply before I actually listened to it on my taranis and now I'm not so sure it's great, but it will do for now!

Thanks for the pack btw, it's great!

**Comment by pinkywafer** [comment]
I see what you mean. We'll redo that one for the next release
